name: casual
dependencies:
  - python=3.8
  - pandas=1.1.3
  - scipy=1.5.2
  - numpy=1.19.1
  - scikit-learn=0.23.2
  - networkx=2.5
  - matplotlib=3.3.1
  - pillow=8.0.0
  - pip
  - pip:
      - ananke-causal-0.1.5
      - dowhy
      - semopy